### ISSUE TITLE
Best way to use a remote schema (introspection endpoint)?

### ISSUE THREAD

**Issue by geekox86** [eturino/apollo-link-scalars#32]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**
What is the best way to use this link with a remote schema (from an introspection endpoint)?

**Comment by eturino** [comment]
@geekox86 Sorry for the delay.

In the projects that I use this link, I use [graphql codegen](https://graphql-code-generator.com/) to get the introspection data of the schema.

`codegen.yml`
```yaml
overwrite: true
documents: null
schema:
  - "http://example.org/graphql"
generates:
  src/__generated__/graphql.schema.json:
    plugins:
      - "introspection"
    config:
      minify: true
```

`src/constants/schema.ts`
```ts
import schemaJSON from "__generated__/graphql.schema.json";
import { buildClientSchema, IntrospectionQuery } from "graphql";
import { parseDayjsOrError } from "@plandek-utils/ts-parse-dayjs";

export const schema = buildClientSchema(schemaJSON);
// note that if you get a type error, it may be an issue with the detected type of the schema. In this case, I force the type `(schemaJSON as unknown) as IntrospectionQuery`

export const typesMap = {
  UTCDate: {
    serialize: (parsed: Dayjs | null) =>
      parsed ? parseDayjsOrError(parsed).toISOString() : null,
    parseValue: (raw: Dayjs | string | number | null): Dayjs | null =>
      raw ? parseDayjsOrError(raw) : null
  }
}
```

then the creation of the link:
```ts
import { schema, typesMap } from "constants/schema";
import { withScalars } from "apollo-link-scalars";

const link = withScalars({
  schema,
  typesMap,
  validateEnums: true,
  removeTypenameFromInputs: true
})
```

I hope you can apply this.
